MEDICAL_KNOWLEDGE = [

    # ── DISEASES ──
    {"id": "d1", "category": "disease", "text": "Diabetes is a chronic condition where blood sugar levels are too high. Symptoms include frequent urination, excessive thirst, fatigue, blurred vision. Type 2 diabetes is most common in India. Department: Endocrinology. Treatment includes lifestyle changes, metformin, insulin."},
    {"id": "d2", "category": "disease", "text": "Hypertension or high blood pressure has no symptoms but causes heart attack and stroke. Normal BP is 120/80. Above 140/90 is hypertension. Department: Cardiology. Treatment: amlodipine, lifestyle changes, low salt diet."},
    {"id": "d3", "category": "disease", "text": "Tuberculosis (TB) is a bacterial infection spread through air. Symptoms: persistent cough over 2 weeks, blood in sputum, fever, night sweats, weight loss. Department: Pulmonology. Free treatment available at government hospitals under RNTCP program."},
    {"id": "d4", "category": "disease", "text": "Dengue fever is spread by Aedes mosquito. Symptoms: high fever, severe headache, pain behind eyes, joint and muscle pain, rash, bleeding. Department: General Medicine. No specific medicine, supportive treatment with fluids."},
    {"id": "d5", "category": "disease", "text": "Kidney stones cause severe pain in back and side, pain during urination, blood in urine. Department: Urology/Nephrology. Treatment: drinking lots of water, pain relief, lithotripsy or surgery for large stones."},
    {"id": "d6", "category": "disease", "text": "Malaria is caused by Plasmodium parasite through mosquito bite. Symptoms: fever with chills, sweating, headache, vomiting. Department: General Medicine. Treatment: chloroquine or artemisinin combination therapy. Free medicines at government hospitals."},
    {"id": "d7", "category": "disease", "text": "Heart attack symptoms include chest pain or pressure, pain in left arm, shortness of breath, sweating, nausea. Medical emergency — call 108 immediately. Department: Cardiology. Treatment: angioplasty, bypass surgery, medicines."},
    {"id": "d8", "category": "disease", "text": "Asthma causes breathing difficulty, wheezing, chest tightness, cough especially at night. Department: Pulmonology. Treatment: inhalers (salbutamol), corticosteroids. Avoid dust, smoke, allergens."},
    {"id": "d9", "category": "disease", "text": "Typhoid is caused by Salmonella bacteria through contaminated food and water. Symptoms: prolonged fever, headache, abdominal pain, constipation or diarrhea. Department: General Medicine. Treatment: ciprofloxacin or azithromycin antibiotics."},
    {"id": "d10", "category": "disease", "text": "Anemia means low hemoglobin in blood. Symptoms: fatigue, weakness, pale skin, shortness of breath, dizziness. Very common in Indian women and children. Treatment: iron tablets, folic acid, diet rich in iron like spinach, jaggery, dates."},

    # ── MEDICINES ──
    {"id": "m1", "category": "medicine", "text": "Paracetamol (Crocin, Dolo 650) is used for fever and mild pain. Adult dose: 500mg to 1000mg every 6-8 hours. Maximum 4g per day. Available at all pharmacies. Do not use in liver disease."},
    {"id": "m2", "category": "medicine", "text": "Metformin is used for Type 2 diabetes to control blood sugar. Take with meals to reduce stomach upset. Common side effects: nausea, diarrhea. Do not use in kidney failure. Available as Glycomet, Glucophage."},
    {"id": "m3", "category": "medicine", "text": "Amlodipine is used for high blood pressure and chest pain. Take once daily. Side effects: ankle swelling, flushing, headache. Available as Amlodip, Stamlo. Do not stop suddenly."},
    {"id": "m4", "category": "medicine", "text": "ORS (Oral Rehydration Solution) is for diarrhea and dehydration. Mix one ORS packet in 1 liter clean water. Give frequently in small sips. Available free at government health centers. Brand names: Electral, Pedialyte."},
    {"id": "m5", "category": "medicine", "text": "Amoxicillin is a common antibiotic for throat infection, ear infection, pneumonia. Dose: 500mg three times daily for 5-7 days. Complete full course even if feeling better. Available at all pharmacies."},
    {"id": "m6", "category": "medicine", "text": "Omeprazole (Omez) is used for acidity, gastric ulcer, GERD. Take 30 minutes before food. Dose: 20mg once daily. Side effects rare but include headache, diarrhea. Safe for long term use under doctor guidance."},
    {"id": "m7", "category": "medicine", "text": "Salbutamol inhaler (Asthalin) is used for asthma and breathing difficulty. Use 2 puffs during attack. Also available as nebulizer solution. Keep inhaler always with you if you have asthma."},

    # ── GOVERNMENT SCHEMES ──
    {"id": "g1", "category": "government_scheme", "text": "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana (PM-JAY) provides health insurance of Rs 5 lakh per family per year. Covers poor and vulnerable families. Valid at empanelled government and private hospitals. Apply at Common Service Centre or hospital help desk with Aadhaar card."},
    {"id": "g2", "category": "government_scheme", "text": "Aarogyasri Health Care Trust in Andhra Pradesh and Telangana provides free treatment for serious diseases like cancer, heart surgery, kidney transplant up to Rs 2.5 lakh. Eligible for BPL families and white ration card holders. Apply at government hospital with ration card and Aadhaar."},
    {"id": "g3", "category": "government_scheme", "text": "Janani Suraksha Yojana (JSY) provides cash assistance to pregnant women for institutional delivery. BPL women get Rs 1400 in rural areas and Rs 1000 in urban areas. Apply at government hospital or ANM health worker during pregnancy."},
    {"id": "g4", "category": "government_scheme", "text": "National Health Mission (NHM) provides free medicines, diagnostics, and treatment at government health centers. Free OPD and IPD services at PHC, CHC, District Hospitals. Dial 104 health helpline for information and medical advice."},
    {"id": "g5", "category": "government_scheme", "text": "RNTCP (Revised National TB Control Programme) provides completely free diagnosis and treatment for Tuberculosis at all government health centers. NIKSHAY portal tracks TB patients. Patients also get Rs 500 per month nutritional support under Nikshay Poshan Yojana."},
    {"id": "g6", "category": "government_scheme", "text": "Pradhan Mantri Suraksha Bima Yojana provides accident insurance of Rs 2 lakh at just Rs 12 per year premium. Available through banks and post offices. For accidental death and permanent disability. Link Aadhaar to bank account to enroll."},
    {"id": "g7", "category": "government_scheme", "text": "Chief Minister's Relief Fund provides financial assistance for serious medical treatment to economically weak patients. Apply through District Collector office with hospital estimate, income certificate, and Aadhaar card. No fixed limit — decided case by case."},
    {"id": "g8", "category": "government_scheme", "text": "ESI (Employees State Insurance) scheme provides medical benefits to organized sector employees earning below Rs 21,000 per month. Covers employee and family for all medical treatment at ESI hospitals. Employer contributes 3.25% and employee contributes 0.75% of wages."},

    # ── HOSPITAL & TREATMENT INFO ──
    {"id": "h1", "category": "hospital_info", "text": "Government hospitals in India provide free or subsidized treatment. OPD consultation is free. Medicines available free from government pharmacy. Best for basic care, TB, maternity, immunization. Bring Aadhaar card and ration card for scheme benefits."},
    {"id": "h2", "category": "hospital_info", "text": "AIIMS (All India Institute of Medical Sciences) is India's top government hospital. Located in Delhi, Bhopal, Bhubaneswar, Jodhpur, Patna, Rishikesh, Mangalagiri (Andhra Pradesh). Provides world-class treatment at government rates. Book appointment online at aiims.edu."},
    {"id": "h3", "category": "hospital_info", "text": "Apollo Hospitals is India's largest private hospital chain with hospitals in Hyderabad, Chennai, Delhi, Bangalore, Kolkata. Known for cardiology, oncology, orthopedics. International quality treatment. Cashless treatment available with most insurance. Call 1860-500-1066."},
    {"id": "h4", "category": "hospital_info", "text": "For emergencies in India call 108 ambulance service — it is free. Available 24/7 across most states. For women in distress call 181. For child helpline call 1098. For health advice call 104 helpline."},
    {"id": "h5", "category": "hospital_info", "text": "District hospitals in each district provide free specialist care including surgery, maternity, pediatrics, orthopedics. They have 24/7 emergency, blood bank, ICU. Fully free for BPL patients. Nominal charges for general patients."},
    {"id": "h6", "category": "hospital_info", "text": "Heart surgery cost in India: Government hospital Rs 50,000 to Rs 1,50,000. Private hospital Rs 2,00,000 to Rs 5,00,000. Covered under Ayushman Bharat for eligible families. Best hospitals: AIIMS, Escort Heart Institute, Apollo, Narayana Health."},
    {"id": "h7", "category": "hospital_info", "text": "Cancer treatment in India: Chemotherapy Rs 10,000-50,000 per cycle. Radiation therapy Rs 1,50,000-5,00,000 for full course. Surgery varies by type. Government cancer hospitals like Tata Memorial Mumbai, Regional Cancer Centre provide subsidized care. Covered under Ayushman Bharat."},
    {"id": "h8", "category": "hospital_info", "text": "Kidney dialysis cost: Government hospital Rs 500-1000 per session. Private hospital Rs 1500-3000 per session. Dialysis needed 2-3 times per week for kidney failure patients. Some states provide free dialysis under government schemes. Apply at District Hospital."},
]